// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZagLUrKxcJmSa68rTsWArN_S6eh-DORc',
    appId: '1:237788288266:web:346e3ca682d0a66870d6f3',
    messagingSenderId: '237788288266',
    projectId: 'sesh-notification',
    authDomain: 'sesh-notification.firebaseapp.com',
    databaseURL: 'https://sesh-notification.firebaseio.com',
    storageBucket: 'sesh-notification.appspot.com',
    measurementId: 'G-5N9SHWW1NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBal6D6FnXdtWeMgYZCb-8HR6x6nf8YOVs',
    appId: '1:237788288266:android:e4871cb3fa49dfaf70d6f3',
    messagingSenderId: '237788288266',
    projectId: 'sesh-notification',
    databaseURL: 'https://sesh-notification.firebaseio.com',
    storageBucket: 'sesh-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhhcY1lSjn_2yPKRDr9vjs0YvDeFleAw',
    appId: '1:237788288266:ios:1ad8b285593dac0570d6f3',
    messagingSenderId: '237788288266',
    projectId: 'sesh-notification',
    databaseURL: 'https://sesh-notification.firebaseio.com',
    storageBucket: 'sesh-notification.appspot.com',
    iosClientId: '237788288266-l10hk6aoi9c4bnb4r1brfblfidufjcvh.apps.googleusercontent.com',
    iosBundleId: 'android',
  );
}
